/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const BeltRouteLazyImport = createFileRoute('/belt')()
const IndexLazyImport = createFileRoute('/')()
const BeltWhatsNewLazyImport = createFileRoute('/belt/whats-new')()

// Create/Update Routes

const BeltRouteLazyRoute = BeltRouteLazyImport.update({
  path: '/belt',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/belt/route.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const BeltWhatsNewLazyRoute = BeltWhatsNewLazyImport.update({
  path: '/whats-new',
  getParentRoute: () => BeltRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/belt/whats-new.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/belt': {
      preLoaderRoute: typeof BeltRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/belt/whats-new': {
      preLoaderRoute: typeof BeltWhatsNewLazyImport
      parentRoute: typeof BeltRouteLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  BeltRouteLazyRoute.addChildren([BeltWhatsNewLazyRoute]),
])

/* prettier-ignore-end */
