/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ColonyImport } from './routes/colony'
import { Route as BeltImport } from './routes/belt'
import { Route as IndexImport } from './routes/index'
import { Route as BeltIndexImport } from './routes/belt.index'
import { Route as BeltWhatsNewImport } from './routes/belt.whats-new'

// Create/Update Routes

const ColonyRoute = ColonyImport.update({
  path: '/colony',
  getParentRoute: () => rootRoute,
} as any)

const BeltRoute = BeltImport.update({
  path: '/belt',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BeltIndexRoute = BeltIndexImport.update({
  path: '/',
  getParentRoute: () => BeltRoute,
} as any)

const BeltWhatsNewRoute = BeltWhatsNewImport.update({
  path: '/whats-new',
  getParentRoute: () => BeltRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/belt': {
      preLoaderRoute: typeof BeltImport
      parentRoute: typeof rootRoute
    }
    '/colony': {
      preLoaderRoute: typeof ColonyImport
      parentRoute: typeof rootRoute
    }
    '/belt/whats-new': {
      preLoaderRoute: typeof BeltWhatsNewImport
      parentRoute: typeof BeltImport
    }
    '/belt/': {
      preLoaderRoute: typeof BeltIndexImport
      parentRoute: typeof BeltImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  BeltRoute.addChildren([BeltWhatsNewRoute, BeltIndexRoute]),
  ColonyRoute,
])

/* prettier-ignore-end */
