/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BeltImport } from './routes/belt'
import { Route as BeltIndexImport } from './routes/belt.index'
import { Route as BeltWhatsNewImport } from './routes/belt.whats-new'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const BeltRoute = BeltImport.update({
  path: '/belt',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const BeltIndexRoute = BeltIndexImport.update({
  path: '/',
  getParentRoute: () => BeltRoute,
} as any)

const BeltWhatsNewRoute = BeltWhatsNewImport.update({
  path: '/whats-new',
  getParentRoute: () => BeltRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/belt': {
      preLoaderRoute: typeof BeltImport
      parentRoute: typeof rootRoute
    }
    '/belt/whats-new': {
      preLoaderRoute: typeof BeltWhatsNewImport
      parentRoute: typeof BeltImport
    }
    '/belt/': {
      preLoaderRoute: typeof BeltIndexImport
      parentRoute: typeof BeltImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  BeltRoute.addChildren([BeltWhatsNewRoute, BeltIndexRoute]),
])

/* prettier-ignore-end */
