name: Deploy Website
on:
    push:
        branches:
            - main

env:
    AWS_REGION: us-west-2

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment: production

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '18'
                  cache: 'yarn'
                  cache-dependency-path: yarn.lock

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: Yarn install
              run: yarn

            - name: Webpack build website
              run: yarn run build
              working-directory: ./website

            - name: Upload website
              run: ./bin/upload.sh
              working-directory: ./website
              env:
                  BUCKET_NAME: websiteBucket
